CREATE DATABASE TERCERFN
USE TERCERFN

--TABLAS SIMPLES
CREATE TABLE CARRERA(
NOCARRERA CHAR(3) PRIMARY KEY,
CARRERA VARCHAR(30),
CHECK (NOCARRERA LIKE 'C[0-9][0-9]'))

CREATE TABLE MATERIA(
NUMMATERIA CHAR(3) PRIMARY KEY,
MATERIA VARCHAR(30),
CHECK (NUMMATERIA LIKE 'M[0-9][0-9]'))

CREATE TABLE TIPO_TEL(
ID_TIPOTEL CHAR(3) PRIMARY KEY,
TIPOTEL VARCHAR(20),
CHECK (ID_TIPOTEL LIKE 'T[0-9][0-9]'))

CREATE TABLE DELEGACION(
ID_DELEGACION CHAR(5) PRIMARY KEY,
DELEGACION VARCHAR(30),
CHECK (ID_DELEGACION LIKE 'DE-[A-Z][0-9]'))

--TABLAS DEPENDIENTES
CREATE TABLE COLONIA(
ID_COLONIA CHAR(5) PRIMARY KEY,
COLONIA VARCHAR(40),
ID_DELEGACION2 CHAR(5) FOREIGN KEY REFERENCES DELEGACION (ID_DELEGACION),
CHECK (ID_COLONIA LIKE 'CO-[A-Z][0-9]'))

CREATE TABLE CALLE(
ID_CALLE CHAR(5) PRIMARY KEY,
CALLE VARCHAR(40),
ID_COLONIA2 CHAR(5) FOREIGN KEY REFERENCES COLONIA (ID_COLONIA),
CHECK (ID_CALLE LIKE 'CA-[A-Z][0-9]'))

CREATE TABLE ALUMNO(
MATRICULA_ALU CHAR(10) PRIMARY KEY,
NOMBRE_ALU VARCHAR(25),
APP_ALU VARCHAR(20),
APM_ALU VARCHAR(20),
ID_DELEGACION1 CHAR(5) FOREIGN KEY REFERENCES DELEGACION (ID_DELEGACION),
ID_COLONIA1 CHAR(5) FOREIGN KEY REFERENCES COLONIA (ID_COLONIA),
ID_CALLE1 CHAR(5) FOREIGN KEY REFERENCES CALLE (ID_CALLE),
NUM_INT VARCHAR(8),
NUM_EXT VARCHAR(8),
CP VARCHAR(5),
NOCARRERA1 CHAR(3) FOREIGN KEY REFERENCES CARRERA (NOCARRERA),
CHECK (MATRICULA_ALU LIKE 'ALU-[A-Z][0-9][0-9][0-9][A-D][D-Z]'))

--TABLAS INTERMEDIAS

CREATE TABLE ALUMNO_MATERIA(
MATRICULA_ALU1 CHAR(10) FOREIGN KEY REFERENCES ALUMNO (MATRICULA_ALU),
NUMMATERIA1 CHAR(3) FOREIGN KEY REFERENCES MATERIA (NUMMATERIA))

CREATE TABLE ALUMNO_TIPOTEL(
ID_TIPOTEL1 CHAR(3) FOREIGN KEY REFERENCES TIPO_TEL (ID_TIPOTEL),
MATRICULA_ALU2 CHAR(10) FOREIGN KEY REFERENCES ALUMNO (MATRICULA_ALU),
TELEFONO BIGINT,
CHECK (TELEFONO >= 0))

-- Insert


--Carrera
INSERT INTO CARRERA VALUES ('C23','SISTEMAS')
INSERT INTO CARRERA VALUES ('C24','GASTRONOMIA')

--Materia
INSERT INTO MATERIA VALUES ('M12','CONTROL INTELIGENTE')
INSERT INTO MATERIA VALUES ('M13','ESTADISTICA')

--Tipo_tel
INSERT INTO TIPO_TEL VALUES ('T18','CELULAR')
INSERT INTO TIPO_TEL VALUES ('T19','CASA')

--Delegación
INSERT INTO DELEGACION VALUES ('DE-B1','BENITO JUAREZ')
INSERT INTO DELEGACION VALUES ('DE-I1','IZTACALCO')

--Colonia
INSERT INTO COLONIA VALUES ('CO-B1','ANZURES','DE-B1')
INSERT INTO COLONIA VALUES ('CO-B2','DEL VALLE','DE-I1')

--Calle
INSERT INTO CALLE VALUES ('CA-A1','ROSA','CO-B1')
INSERT INTO CALLE VALUES ('CA-B1','AZUL','CO-B2')

--Alumno
INSERT INTO ALUMNO VALUES ('ALU-A123BM','ANA','ORTIZ','ESTRADA','DE-B1','CO-B1','CA-A1','10A','204','89090','C23')

--Alumno_materia
INSERT INTO ALUMNO_MATERIA VALUES ('ALU-A123BM','M12')

--Alumno_tipotel
INSERT INTO ALUMNO_TIPOTEL VALUES ('T18','ALU-A123BM',67676767)