Create database hotel

use hotel

CREATE TABLE RECEPCIONISTA(
COD_REC CHAR(4)		NOT NULL,
APE_PAT	CHAR(18)	NOT NULL,
APE_MAT	CHAR(18)	NOT NULL,
NOMBRES	CHAR(20)	NOT NULL,
DIRECTI	CHAR(25)	NOT NULL,
TELEFON	CHAR(9)		NOT NULL,
FECHANA DATE		NOT NULL,

PRIMARY KEY (COD_REC),

CHECK (COD_REC LIKE 'R[0-9][0-9][0-9]')
);

CREATE TABLE HUESPED(
COD_HUE CHAR(4)		NOT NULL,
APE_PAT	CHAR(18)	NOT NULL,
APE_MAT	CHAR(18)	NOT NULL,
NOMBRES	CHAR(20)	NOT NULL,
NACION	CHAR(25)	NOT NULL,
TIPO_DOC	CHAR(9)		NOT NULL,
NUM_DOC DATE		NOT NULL,
SEXO CHAR(20)

PRIMARY KEY (COD_HUE),

CHECK (COD_HUE LIKE 'H[0-9][0-9][0-9]')
);

CREATE TABLE CLASIFICACION(
TIPO_CLA CHAR(3) NOT NULL,
DETALLE VARCHAR(55),
DESCRIP VARCHAR(55),

PRIMARY KEY (TIPO_CLA),

CHECK (TIPO_CLA LIKE 'C[0-9][0-9]')
);

CREATE TABLE HABITACION(
NUM_HAB INT IDENTITY NOT NULL,
TIPO	CHAR(25) NOT NULL,
PISO	SMALLINT	NOT NULL,
BAÑO	SMALLINT	NOT NULL,
AGUA_CAL BIT  DEFAULT 1,
VISTA_MAR	BIT  DEFAULT 1,
NUM_CAMAS SMALLINT	DEFAULT 1 NOT NULL,
PRECIO MONEY NOT NULL,
TIPO_CLA CHAR(3) NOT NULL,

PRIMARY KEY (NUM_HAB),
FOREIGN KEY (TIPO_CLA) References CLASIFICACION(TIPO_CLA)
);


CREATE TABLE FICHA_ESTADO(
NRO_FICHA INT NOT NULL,
NRO_HAB INT NOT NULL,
FECHA_HORA DATETIME NOT NULL,
ACTIVO CHAR(50),
DETALLE VARCHAR(100)
);

CREATE TABLE BOLETA(
NRO_BOLE INT IDENTITY,
ORDEN CHAR(25),
FECHA DATETIME NOT NULL,

PRIMARY KEY (NRO_BOLE)
);

CREATE TABLE PRODUCTOS(
COD_PRO VARCHAR(3) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
PRECIO MONEY NOT NULL,

PRIMARY KEY (COD_PRO),

CHECK (COD_PRO LIKE 'P[0-9][0-9]')
);

CREATE TABLE DETALLE_BOLETA(
NRO_BOLE INT ,
COD_PROD VARCHAR(3) NOT NULL,
PRECIO MONEY NOT NULL,
CANTIDAD INT default 0 NOT NULL,
IMPORTE AS PRECIO * CANTIDAD,

Foreign key (NRO_BOLE) References BOLETA(NRO_BOLE),
Foreign key (COD_PROD) References PRODUCTOS(COD_PRO)
);

CREATE TABLE RESERVA_HABITACION(
ORDEN INT IDENTITY,
NRO_HAB INT NOT NULL,
FECHA_HORA_INGRESO DATETIME NOT NULL,
FECHA_HORA_SALIDA DATETIME NOT NULL,
COD_REC CHAR(4) NOT NULL,

PRIMARY KEY (ORDEN),

Foreign key (NRO_HAB) References HABITACION(NUM_HAB),
Foreign key (COD_REC) References RECEPCIONISTA(COD_REC)
);

--ESTA TABLA NO ESTA CREADA TODAVIA
CREATE TABLE HUESPED_LIBRO(
CODI_HUES CHAR(4) NOT NULL,
ORDEN INT NOT NULL,

Foreign key (CODI_HUES) References HUESPED(COD_HUE),
Foreign key (ORDEN) References RESERVA_HABITACION(ORDEN)
);