CREATE DATABASE SUPERMERCADO;
GO
USE SUPERMERCADO;
GO
CREATE TABLE Clientes(
	DNI VARCHAR(9) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(60) NOT NULL
);

GO
INSERT INTO Clientes(DNI,NOMBRE,DIRECCION) VALUES
('023502259','Juan Perez','Av. Lima 873'),
('023503259','Gabriela Blaudi','Av. Arequipa 3'),
('021502259','Fernando Garcia','Av. Bracil 98'),
('023502209','Carlos Sanches','Av. Chicha 56'),
('023512259','Ana Martines','Av. Junin 765');


GO
CREATE TABLE Sucursales ( 
  NSUC VARCHAR(4) NOT NULL PRIMARY KEY,
  CIUDAD  VARCHAR(30)
);

GO

CREATE TABLE Cuentas ( 
  COD VARCHAR(4) NOT NULL,
  DNI VARCHAR(9) NOT NULL,
  NSUCURS VARCHAR(4) NOT NULL,
  SALDO INT DEFAULT 0,
  PRIMARY KEY (COD, DNI, NSUCURS),
  FOREIGN KEY (DNI) REFERENCES Clientes (DNI),
  FOREIGN KEY (NSUCURS) REFERENCES Sucursales (NSUC) );
GO
SELECT * FROM Sucursales;
GO
SELECT * FROM Cuentas;
GO

GO
SELECT * FROM Clientes;
GO

SELECT * FROM Clientes;



